/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Clases.Mascota;
import Clases.PersistenciaMascota;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nixia
 */
public class F8EliminarMascota extends javax.swing.JInternalFrame {

     DefaultListModel listModel = new DefaultListModel();
    ArrayList<Mascota> animal = new ArrayList<Mascota>();

    DefaultTableModel modelo = new DefaultTableModel();
    
    public F8EliminarMascota() {
        initComponents();
        tblMascota.getColumnCount();
        modelo = (DefaultTableModel) tblMascota.getModel();
         LLenarJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMascota = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tblMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLIENTE", "DNI", "MASCOTA", "RAZA", "COLOR", "PESO", "SEXO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMascota);

        jButton1.setText("Elimina Mascota");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  int eliminarDatos = tblMascota.getSelectedRow();
        
        if (eliminarDatos >= 0) {
            ArrayList<Mascota> listado= PersistenciaMascota.LoadData();
            listado.remove(eliminarDatos);
            PersistenciaMascota.SaveData(listado);
            modelo.removeRow(eliminarDatos);
            
           
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un dato de la tabla");

        }
    }//GEN-LAST:event_jButton1ActionPerformed
void LimpiarJTable(){
  DefaultTableModel df = ((DefaultTableModel)tblMascota.getModel());
  int a = df.getRowCount() -1;
  for (int i = a; i >=0; i--){
      df.removeRow(i);
  }
}
void LLenarJTable(){
    
    ArrayList<Mascota> lista = PersistenciaMascota.LoadData();
    DefaultTableModel df = ((DefaultTableModel) tblMascota.getModel());
    for(Mascota a : lista){
    df.addRow(new Object[]{a.getNombreClient(),a.getDni(), a.getNombreMascot(), a.getRaza(),
            a.getColor(),a.getPeso(),a.getSexo()});
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMascota;
    // End of variables declaration//GEN-END:variables
}
